---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-addon-io-v1-advancedjob
  failurePolicy: Fail
  name: madvancedjob.kb.io
  rules:
  - apiGroups:
    - apps.addon.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - advancedjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-addon-io-v1-advancedjob
  failurePolicy: Fail
  name: vadvancedjob.kb.io
  rules:
  - apiGroups:
    - apps.addon.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - advancedjobs
  sideEffects: None
