# permissions for end users to view advancedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: advancedjob-viewer-role
rules:
- apiGroups:
  - apps.addon.io
  resources:
  - advancedjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.addon.io
  resources:
  - advancedjobs/status
  verbs:
  - get
