# permissions for end users to edit advancedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: advancedjob-editor-role
rules:
- apiGroups:
  - apps.addon.io
  resources:
  - advancedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.addon.io
  resources:
  - advancedjobs/status
  verbs:
  - get
