apiVersion: apps.addon.io/v1
kind: AdvancedJob
metadata:
  name: advancedjob-sample1
  namespace: dev
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          imagePullPolicy: IfNotPresent
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - echo "hello"
