apiVersion: batch/v1
kind: Job
metadata:
  namespace: dev
  name: myjob
spec:
  completions: 8
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          imagePullPolicy: IfNotPresent
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - echo "hello"
